export const REALTIME_ADD_WIDGET_TOOL_NAME = "board.add_widget";

export const realtimeWidgetAliases: Record<string, string[]> = {
  note: ["便签", "笔记"],
  todo: ["待办", "任务", "清单"],
  tv: ["电视", "直播"],
  music: ["音乐", "歌曲", "歌", "播放器"],
  worldClock: ["世界时钟", "世界时间", "时区"],
  dialClock: ["时钟", "表盘", "钟表"],
  translate: ["翻译"],
  converter: ["换算", "单位"],
  clipboard: ["剪贴板"],
  recorder: ["录音"],
  messageBoard: ["留言板", "留言"],
  weather: ["天气"],
  countdown: ["倒计时", "计时器"],
  headline: ["新闻", "头条"],
  market: ["行情", "股票", "指数"],
  calculator: ["计算器"]
};

export const realtimeToolSelectionPolicyLines = [
  "只要用户有明确小桌板操作意图，就选择最接近的已注册工具；不要因为需要确认、可能失败、缺少当前状态或包含条件句就回复“没有工具”。确认、目标解析和失败处理由本地 Harness 继续处理。",
  "日志、监控、诊断、工具目录、分级加载、模块加载、工具调用失败、前端成功状态、弱网、断线、重连、重复回复、记录错误、导出语音诊断摘要时，选择 assistant.runtime_diagnostics。",
  "如果一句话同时包含诊断词和明确动作，例如“关闭留言板的本地解析置信度低就交给 realtime”，明确动作优先，选择 widget.remove 等动作工具。",
  "如果用户说“打开 + 小工具名”，优先添加这个小工具；只有用户明确说切到、聚焦、回到已有窗口时才聚焦。",
  "打开电视、打开钟表、打开时钟、打开世界时钟、打开留言板、打开天气、打开行情、打开新闻、打开录音机、打开便签、打开待办、打开剪贴板、打开翻译或计算器等窗口类命令必须选择 board.add_widget；如果还要求播放、查询、刷新、发送或写入，后续阶段再补对应工具。",
  "再打开一个倒计时/再打开一个计时器是打开新小工具实例，选择 board.add_widget；不要误选 countdown.set。",
  "打开电视/先打开电视/打开 CCTV/播放 CCTV 前如果语义包含打开窗口，必须选择 board.add_widget，再选择 tv.play 或 tv.select_channel。",
  "打开天气/打开世界时钟/打开新闻/打开行情时，必须选择 board.add_widget，并选择 weather.set_city/worldClock.set_zones/headline.request_refresh/market.set_indices。",
  "打开音乐播放器并搜索/播放时，必须选择 board.add_widget，并选择 music.search 或 music.play。",
  "如果工具目录没加载完但用户要求打开音乐，仍选择 board.add_widget；如果要求播放具体歌曲且缺音乐工具，仍选择 music.play。",
  "打开上证和深证行情、打开市场行情、打开财经行情这类打开行情窗口请求，必须选择 board.add_widget 和 market.set_indices。",
  "查某地天气并提醒我/如果冷就提醒/明天出门先查天气再提醒时，同时选择 weather.set_city 和 todo.add_item。",
  "用户只说“打开时钟”时，目标是 dialClock/表盘时钟；只有明确说世界时钟、世界时间、时区或城市时间时才选 worldClock。",
  "music.search 和 music.play 只用于明确搜索/播放/暂停/切换音乐；非音乐窗口名即使当前焦点在音乐播放器，也不要传给音乐工具。",
  "用户说“整理桌面/排列桌面/对齐小工具”时，优先调用 board.auto_align。",
  "用户说“隐藏/显示/收起/展开侧栏/侧边栏”时，优先调用 app.sidebar.set。",
  "用户说“小桌板全屏/进入全屏/退出全屏”时，优先调用 app.fullscreen.set；不要误选 widget.fullscreen_focus。",
  "用户说“全屏看电视/电视全屏/CCTV 全屏”时，优先调用 tv.fullscreen 和 widget.fullscreen_focus；不要误选 app.fullscreen.set。",
  "用户说“打开设置/显示设置菜单”时，优先调用 app.settings.open。",
  "用户说“打开搜索/命令面板”时，优先调用 app.command_palette.open；用户说“打开 AI 生成”时，优先调用 app.ai_dialog.open。",
  "如果用户说“关闭/关掉 + 小工具名”，优先调用 widget.remove 关闭这个小工具窗口。",
  "如果用户要求调整窗口、面板、封面、文字、按钮、位置或大小，优先选择 widget.move / widget.resize / widget.focus；不要把这类界面布局请求误选成播放、搜索、刷新、写入或发送内容。",
  "别盖住、避免挡住、不要遮住、恢复正常大小、排成一列、控件居中、登录按钮右上角这类界面布局请求优先选择 widget.move 或 widget.resize；不要回复无法处理。",
  "放最前、置顶、最前面必须选择 widget.bring_to_front；通常还要选择 widget.focus。",
  "用户说“来个/来一首/我要听/播放/给我放 + 歌手、歌曲或明确播放意图”时，默认调用 music.play；明确说搜索/找/重新搜索/不一定播放/先不播放/不要播放，或只是轻松、放松、背景、睡前等模糊风格探索时，调用 music.search。",
  "播放/给我一首/换成/专注模式用的播放列表/播放轻音乐/播放舒缓钢琴，即使是风格词，也表示要开始播放，选择 music.play。",
  "搜索/搜 + 关键词 + 然后播放第一个结果时，同时选择 music.search 和 music.play；找 + 明确歌手和歌名并带播放前确认时，选择 music.play。",
  "换成轻松一点、不要继续现在的歌曲、不要沿用上一首时，必须选择 music.search 重新搜索。",
  "用户说“找 + 明确歌手和歌名”且表达别只放试听/不要试听时，选择 music.play；音乐登录、授权、试听片段、完整播放、已登录账号但仍试听时，选择 music.auth_status。",
  "检查有没有登录音乐入口、查看音乐登录入口时，也选择 music.auth_status；可以同时选择 app.settings.open，但不要自然回复。",
  "用户说“提醒我/叫我/别忘了/有空提醒”时选择 todo.add_item；如果有明确几分钟后/倒计时，也在规划阶段包含 countdown.set。",
  "用户说复制、保存、固定保存、口令、验证码、token、项目名到剪贴板时选择 clipboard.add_text；清理、清空剪贴板时选择 clipboard.clear，即使需要确认也不要改成 assistant.reply。",
  "用户说先确认、确认后、如果没有、保留 pinned、保留正在运行的等约束时，仍选择对应动作工具；确认和约束执行由本地 Harness 处理，不要改成 assistant.reply。",
  "用户说留言板发送、回复、发一句时选择 messageBoard.send；用户说关闭留言板时选择 widget.remove，不要发送“关闭”。",
  "用户说“我说关闭 X 时执行关闭，不是发送/不是回复”仍然是关闭命令，选择 widget.remove。",
  "新闻摘要追加到便签、新闻备忘、天气摘要发到留言板这类跨工具摘要命令，需要同时选择来源工具和目标工具。",
  "翻译成英文备忘、写入备忘、追加到便签时，必须选择 note.write。",
  "新闻和天气并排、新闻窗口和天气窗口一起显示时，必须选择 headline.request_refresh、weather.set_city 和 widget.move。",
  "本地路径、当前歌曲名、普通文本复制到剪贴板时选择 clipboard.add_text，不要因为路径或当前状态而自然回复。",
  "录音之前/开始录音之前如果要求先关闭电视声音，同时选择 tv.pause 和 recorder.start。",
  "发送消息前先确认内容时，仍选择 messageBoard.send；关闭音乐和电视之前先确认一次时，仍选择 widget.remove。",
  "缩小窗口且避免挡住其他窗口时，同时选择 widget.resize 和 widget.move。",
  "删除/关闭临时倒计时或临时小工具时选择 widget.remove，不要误选 countdown.reset。",
  "如果用户说“暂停/继续/播放/下一首”等播放控制，优先调用对应媒体工具；点歌、歌手名加歌曲名时选择 music.play。"
];

export const realtimeToolSelectionSessionPolicyLines = [
  "如果用户只是问候、确认你是否在线、闲聊，或没有明确小桌板操作意图，不要调用工具，直接用一句很短的中文自然回复。",
  "只要用户有明确小桌板操作意图，就选择最接近的已注册工具；不要因为需要确认、可能失败、缺少当前状态或包含条件句就回复“没有工具”。确认、目标解析和失败处理由本地 Harness 继续处理。",
  "日志、监控、诊断、工具目录、分级加载、模块加载、工具调用失败、前端成功状态、弱网、断线、重连、重复回复、记录错误、导出语音诊断摘要时，选择 assistant.runtime_diagnostics。",
  "如果一句话同时包含诊断词和明确动作，例如“关闭留言板的本地解析置信度低就交给 realtime”，明确动作优先，选择 widget.remove 等动作工具。",
  "如果用户要求播放某首歌、某位歌手或某张专辑，并且工具目录里有 music.play，直接选择 music.play，不要先选择 widget.focus 或 board.add_widget。",
  "如果用户说“打开 + 小工具名”，并且工具目录里有 board.add_widget，优先选择 board.add_widget；只有用户明确说切到、聚焦、回到已有窗口时才选择 widget.focus。",
  "打开电视、打开钟表、打开时钟、打开世界时钟、打开留言板、打开天气、打开行情、打开新闻、打开录音机、打开便签、打开待办、打开剪贴板、打开翻译或计算器等窗口类命令必须选择 board.add_widget；如果还要求播放、查询、刷新、发送或写入，前端会继续加载对应工具。",
  "再打开一个倒计时/再打开一个计时器是打开新小工具实例，选择 board.add_widget；不要误选 countdown.set。",
  "打开电视/先打开电视/打开 CCTV/播放 CCTV 前如果语义包含打开窗口，必须选择 board.add_widget，再选择 tv.play 或 tv.select_channel。",
  "打开天气/打开世界时钟/打开新闻/打开行情时，必须选择 board.add_widget，并选择 weather.set_city/worldClock.set_zones/headline.request_refresh/market.set_indices。",
  "打开音乐播放器并搜索/播放时，必须选择 board.add_widget，并选择 music.search 或 music.play。",
  "如果工具目录没加载完但用户要求打开音乐，仍选择 board.add_widget；如果要求播放具体歌曲且缺音乐工具，仍选择 music.play。",
  "打开上证和深证行情、打开市场行情、打开财经行情这类打开行情窗口请求，必须选择 board.add_widget 和 market.set_indices。",
  "查某地天气并提醒我/如果冷就提醒/明天出门先查天气再提醒时，同时选择 weather.set_city 和 todo.add_item。",
  "用户只说“打开时钟”时，目标是 dialClock/表盘时钟；只有明确说世界时钟、世界时间、时区或城市时间时才选 worldClock。",
  "music.search 和 music.play 只用于明确搜索/播放/暂停/切换音乐；非音乐窗口名即使当前焦点在音乐播放器，也不要传给音乐工具。",
  "用户说“整理桌面/排列桌面/对齐小工具”时，优先选择 board.auto_align。",
  "用户说“隐藏/显示/收起/展开侧栏/侧边栏”时，优先选择 app.sidebar.set。",
  "用户说“小桌板全屏/进入全屏/退出全屏”时，优先选择 app.fullscreen.set；不要误选 widget.fullscreen_focus。",
  "用户说“全屏看电视/电视全屏/CCTV 全屏”时，优先选择 tv.fullscreen 和 widget.fullscreen_focus；不要误选 app.fullscreen.set。",
  "用户说“打开设置/显示设置菜单”时，优先选择 app.settings.open。",
  "用户说“打开搜索/命令面板”时，优先选择 app.command_palette.open；用户说“打开 AI 生成”时，优先选择 app.ai_dialog.open。",
  "如果用户说“关闭/关掉 + 小工具名”，优先选择 widget.remove 关闭这个小工具窗口。",
  "如果用户要求调整窗口、面板、封面、文字、按钮、位置或大小，优先选择 widget.move / widget.resize / widget.focus；不要把这类界面布局请求误选成播放、搜索、刷新、写入或发送内容。",
  "别盖住、避免挡住、不要遮住、恢复正常大小、排成一列、控件居中、登录按钮右上角这类界面布局请求优先选择 widget.move 或 widget.resize；不要回复无法处理。",
  "放最前、置顶、最前面必须选择 widget.bring_to_front；通常还要选择 widget.focus。",
  "用户说“来个/来一首/我要听/播放/给我放 + 歌手、歌曲或明确播放意图”时，默认选择 music.play；明确说搜索/找/重新搜索/不一定播放/先不播放/不要播放，或只是轻松、放松、背景、睡前等模糊风格探索时，选择 music.search。",
  "播放/给我一首/换成/专注模式用的播放列表/播放轻音乐/播放舒缓钢琴，即使是风格词，也表示要开始播放，选择 music.play。",
  "搜索/搜 + 关键词 + 然后播放第一个结果时，同时选择 music.search 和 music.play；找 + 明确歌手和歌名并带播放前确认时，选择 music.play。",
  "换成轻松一点、不要继续现在的歌曲、不要沿用上一首时，必须选择 music.search 重新搜索。",
  "用户说“找 + 明确歌手和歌名”且表达别只放试听/不要试听时，选择 music.play；音乐登录、授权、试听片段、完整播放、已登录账号但仍试听时，选择 music.auth_status。",
  "检查有没有登录音乐入口、查看音乐登录入口时，也选择 music.auth_status；可以同时选择 app.settings.open，但不要自然回复。",
  "用户说“提醒我/叫我/别忘了/有空提醒”时选择 todo.add_item；如果有明确几分钟后/倒计时，规划阶段会包含 countdown.set。",
  "用户说复制、保存、固定保存、口令、验证码、token、项目名到剪贴板时选择 clipboard.add_text；清理、清空剪贴板时选择 clipboard.clear，即使需要确认也不要改成自然回复。",
  "用户说先确认、确认后、如果没有、保留 pinned、保留正在运行的等约束时，仍选择对应动作工具；确认和约束执行由本地 Harness 处理，不要改成自然回复。",
  "用户说留言板发送、回复、发一句时选择 messageBoard.send；用户说关闭留言板时选择 widget.remove，不要发送“关闭”。",
  "用户说“我说关闭 X 时执行关闭，不是发送/不是回复”仍然是关闭命令，选择 widget.remove。",
  "新闻摘要追加到便签、新闻备忘、天气摘要发到留言板这类跨工具摘要命令，需要同时选择来源工具和目标工具。",
  "翻译成英文备忘、写入备忘、追加到便签时，必须选择 note.write。",
  "新闻和天气并排、新闻窗口和天气窗口一起显示时，必须选择 headline.request_refresh、weather.set_city 和 widget.move。",
  "本地路径、当前歌曲名、普通文本复制到剪贴板时选择 clipboard.add_text，不要因为路径或当前状态而自然回复。",
  "录音之前/开始录音之前如果要求先关闭电视声音，同时选择 tv.pause 和 recorder.start。",
  "发送消息前先确认内容时，仍选择 messageBoard.send；关闭音乐和电视之前先确认一次时，仍选择 widget.remove。",
  "缩小窗口且避免挡住其他窗口时，同时选择 widget.resize 和 widget.move。",
  "删除/关闭临时倒计时或临时小工具时选择 widget.remove，不要误选 countdown.reset。",
  "如果用户说“暂停/继续/播放/下一首”等播放控制，优先选择对应媒体工具。"
];

export const realtimePlanSelectionPolicyLines = [
  "只要用户有明确小桌板操作意图，就选择最接近的已注册工具；不要因为需要确认、可能失败、缺少当前状态或包含条件句就回复“没有工具”。确认、目标解析和失败处理由本地 Harness 继续处理。",
  "日志、监控、诊断、工具目录、分级加载、模块加载、工具调用失败、前端成功状态、弱网、断线、重连、重复回复、记录错误、导出语音诊断摘要时，选择 assistant.runtime_diagnostics。",
  "如果一句话同时包含诊断词和明确动作，例如“关闭留言板的本地解析置信度低就交给 realtime”，明确动作优先，选择 widget.remove 等动作工具。",
  "用户要求播放某首歌、某位歌手或某张专辑，并且工具目录里有 music.play，必须选择 music.play。",
  "用户说“来个/来一首/我要听/播放/给我放 + 歌手、歌曲或明确播放意图”时，默认选择 music.play；明确说搜索/找/重新搜索/不一定播放/先不播放/不要播放，或只是轻松、放松、背景、睡前等模糊风格探索时，选择 music.search。",
  "打开电视、打开钟表、打开时钟、打开世界时钟、打开留言板、打开天气、打开行情、打开新闻、打开录音机、打开便签、打开待办、打开剪贴板、打开翻译或计算器等窗口类命令必须选择 board.add_widget；如果还要求播放、查询、刷新、发送或写入，同时选择对应工具。",
  "再打开一个倒计时/再打开一个计时器是打开新小工具实例，选择 board.add_widget；不要选择 countdown.set。",
  "打开电视/先打开电视/打开 CCTV/播放 CCTV 前如果语义包含打开窗口，必须选择 board.add_widget，再选择 tv.play 或 tv.select_channel。",
  "打开天气/打开世界时钟/打开新闻/打开行情时，必须选择 board.add_widget，并选择 weather.set_city/worldClock.set_zones/headline.request_refresh/market.set_indices。",
  "打开音乐播放器并搜索/播放时，必须选择 board.add_widget，并选择 music.search 或 music.play。",
  "如果工具目录没加载完但用户要求打开音乐，仍选择 board.add_widget；如果要求播放具体歌曲且缺音乐工具，仍选择 music.play。",
  "打开上证和深证行情、打开市场行情、打开财经行情这类打开行情窗口请求，必须选择 board.add_widget 和 market.set_indices。",
  "查某地天气并提醒我/如果冷就提醒/明天出门先查天气再提醒时，同时选择 weather.set_city 和 todo.add_item。",
  "用户只说“打开时钟”时选择 board.add_widget 且 selectedModule/targetHint 指向 dialClock/表盘；只有明确说世界时钟、世界时间、时区或城市时间时才指向 worldClock。",
  "music.search 和 music.play 只用于明确搜索/播放/暂停/切换音乐；非音乐窗口名即使当前焦点在音乐播放器，也不要传给音乐工具。",
  "用户说“整理桌面/排列桌面/对齐小工具”时，必须选择 board.auto_align。",
  "用户说“隐藏/显示侧栏、进入/退出全屏、打开设置、打开搜索/命令面板、打开 AI 生成”时，必须选择对应 app.* 工具。",
  "用户说“全屏看电视/电视全屏/CCTV 全屏”时，必须选择 tv.fullscreen 和 widget.fullscreen_focus；不要选择 app.fullscreen.set。",
  "用户要求调整窗口、面板、封面、文字、按钮、位置或大小时，必须选择 widget.move / widget.resize / widget.focus 或对应 app.* 工具；不要选择播放、搜索、刷新、写入、待办或留言工具。",
  "别盖住、避免挡住、不要遮住、恢复正常大小、排成一列、控件居中、登录按钮右上角这类界面布局请求必须选择 widget.move 或 widget.resize；不要选择 assistant.reply。",
  "放最前、置顶、最前面必须选择 widget.bring_to_front；通常还要选择 widget.focus。",
  "播放/给我一首/换成/专注模式用的播放列表/播放轻音乐/播放舒缓钢琴，即使是风格词，也表示要开始播放，选择 music.play。",
  "搜索/搜 + 关键词 + 然后播放第一个结果时，同时选择 music.search 和 music.play；找 + 明确歌手和歌名并带播放前确认时，选择 music.play。",
  "换成轻松一点、不要继续现在的歌曲、不要沿用上一首时，必须选择 music.search 重新搜索。",
  "用户说“提醒我/叫我/别忘了/有空提醒”时选择 todo.add_item；如果有明确几分钟后/倒计时，同时选择 countdown.set。",
  "用户说复制、保存、固定保存、口令、验证码、token、项目名到剪贴板时选择 clipboard.add_text；清理、清空剪贴板时选择 clipboard.clear。",
  "用户说先确认、确认后、如果没有、保留 pinned、保留正在运行的等约束时，仍选择对应动作工具；确认和约束执行由本地 Harness 处理，不要选择 assistant.reply。",
  "用户说留言板发送、回复、发一句时选择 messageBoard.send；用户说关闭留言板时选择 widget.remove，不要发送“关闭”。",
  "用户说“我说关闭 X 时执行关闭，不是发送/不是回复”仍然是关闭命令，选择 widget.remove。",
  "新闻摘要追加到便签、新闻备忘、天气摘要发到留言板这类跨工具摘要命令，需要同时选择来源工具和目标工具。",
  "翻译成英文备忘、写入备忘、追加到便签时，必须选择 note.write。",
  "新闻和天气并排、新闻窗口和天气窗口一起显示时，必须选择 headline.request_refresh、weather.set_city 和 widget.move。",
  "本地路径、当前歌曲名、普通文本复制到剪贴板时选择 clipboard.add_text，不要因为路径或当前状态而选择 assistant.reply。",
  "录音之前/开始录音之前如果要求先关闭电视声音，同时选择 tv.pause 和 recorder.start。",
  "检查有没有登录音乐入口、查看音乐登录入口时，也选择 music.auth_status；可以同时选择 app.settings.open，但不要选择 assistant.reply。",
  "发送消息前先确认内容时，仍选择 messageBoard.send；关闭音乐和电视之前先确认一次时，仍选择 widget.remove。",
  "缩小窗口且避免挡住其他窗口时，同时选择 widget.resize 和 widget.move。"
];

export function inputMentionsRealtimeWidgetType(input: string | undefined, type: string): boolean {
  const text = input ?? "";
  return (realtimeWidgetAliases[type] ?? []).some((alias) => text.includes(alias));
}

export function findRealtimeWidgetType(input: string | undefined, targetHint?: string): string | undefined {
  return Object.keys(realtimeWidgetAliases).find(
    (type) => inputMentionsRealtimeWidgetType(input, type) || inputMentionsRealtimeWidgetType(targetHint, type)
  );
}
